name: Publish NuGet Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Update NuGet
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"

      # Install GitVersion to automatically create a semantic
      # version from your repository:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      # Run GitVersion (set an ID to later fetch values)
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - run: dotnet build src/CachePackage.sln -c Release /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.Sha }}
      - run: dotnet test src/CachePackage.sln
      - run: dotnet pack src/HexMaster.RedisCache/HexMaster.RedisCache.csproj -c Release -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:InformationalVersion=${{ steps.gitversion.outputs.Sha }} -p:PackageVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}
      - run: dotnet pack src/HexMaster.RedisCache.Abstractions/HexMaster.RedisCache.Abstractions.csproj -c Release -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:InformationalVersion=${{ steps.gitversion.outputs.Sha }} -p:PackageVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: abstractions-package
          path: src/HexMaster.RedisCache.Abstractions/bin/Release/*${{ steps.gitversion.outputs.MajorMinorPatch }}.nupkg
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: core-package
          path: src/HexMaster.RedisCache/bin/Release/*${{ steps.gitversion.outputs.MajorMinorPatch }}.nupkg
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    name: Deploy NuGet Package
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: abstractions-package
          path: ./abstractions
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: core-package
          path: ./core
      - name: Publish
        run: nuget push abstractions/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
      - name: Publish
        run: nuget push core/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
